// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZT86rKL9DVl4wpHxXtSMfDHxjeKZbQE',
    appId: '1:593658875969:web:111471d09c2c7f81e9f6c0',
    messagingSenderId: '593658875969',
    projectId: 'fitness-app-86445',
    authDomain: 'fitness-app-86445.firebaseapp.com',
    storageBucket: 'fitness-app-86445.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgJ4Ky4C79oJnsCOIdBpCnY8M2XWracrw',
    appId: '1:593658875969:android:0daf805d8d44978de9f6c0',
    messagingSenderId: '593658875969',
    projectId: 'fitness-app-86445',
    storageBucket: 'fitness-app-86445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpkCv5C-NIxm2rGoNzT0aZz00wm_NPb7g',
    appId: '1:593658875969:ios:ff1309705437be1ae9f6c0',
    messagingSenderId: '593658875969',
    projectId: 'fitness-app-86445',
    storageBucket: 'fitness-app-86445.firebasestorage.app',
    iosBundleId: 'com.binodcoder.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpkCv5C-NIxm2rGoNzT0aZz00wm_NPb7g',
    appId: '1:593658875969:ios:04ec362ee3c2a5abe9f6c0',
    messagingSenderId: '593658875969',
    projectId: 'fitness-app-86445',
    storageBucket: 'fitness-app-86445.firebasestorage.app',
    iosBundleId: 'com.example.myBlogBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQZT86rKL9DVl4wpHxXtSMfDHxjeKZbQE',
    appId: '1:593658875969:web:c725cbb022725646e9f6c0',
    messagingSenderId: '593658875969',
    projectId: 'fitness-app-86445',
    authDomain: 'fitness-app-86445.firebaseapp.com',
    storageBucket: 'fitness-app-86445.firebasestorage.app',
  );
}
